export default {
  'color-accent': '#f5a00c',
  'color-accent-dark': '#f5700c',
  'color-primary': '#28d602',
  'color-primary-dark': '#28d602',
  'color-error': '#f5420c',
  'color-success': '#f5a00c',
  'preferred-font': 'system-ui, arial',
  'gutter-inline': '0.5em',
  'gutter-inline-large': '1em',
  'font-size': '1.2em',
  'font-size-tiny': '0.6em',
  'font-size-small': '0.8em',
  'font-size-normal': '1em',
  'font-size-big': '1.5em',
  'icon-size-medium': '2.5em',
};
